version: '3'

services:
  warehouseDatabase:
    image: mysql:5-debian
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
  adminer:
    image: adminer
    ports:
      - 8080:8080
  authenticationDatabase:
    image: mysql:5-debian
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
  redis:
    image: redis
    ports:
      - 6379:6379
